apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-app-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: metrics-app
  endpoints:
  - port: http
    interval: 15s
    path: /metrics
