apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress", "--vm", "1", "--vm-bytes", "128M"]
    resources:
      limits:
        memory: 64Mi
  restartPolicy: Never
