apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
spec:
  containers:
  - name: huge
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "100"
        memory: "512Gi"
  restartPolicy: Never
